language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

install: "(cd src && pip install -U pip && pip install -r requirements.txt && pip install -r requirements-dev.txt && pip install .)"

script: "cd src && python setup.py test"
